# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.2

branches:
  only:
    - master
    - develop

script:
  - xctool -project OYThisUI.xcodeproj -scheme OYThisUI build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=NO

after_success:
  - bash <(curl -s https://codecov.io/bash)