# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.2
branches:
  only:
    - master
    - develop
script:
- xctool -project OYThisUI.xcodeproj -scheme OYThisUI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -project OYThisUI.xcodeproj -scheme OYThisUI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

before_install:
  - pip install codecov
after_success:
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)